name: person_module
services:
  person_module:
    container_name: person_module
    image: ghcr.io/ad-sdl/person_module
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/person_module:latest
        - ghcr.io/ad-sdl/person_module:dev
    command: python person_module/src/person_rest_node.py --node_definition definitions/person_node_template.node.yaml
    volumes:
      - ./definitions:/home/madsci/definitions
    privileged: true
    network_mode: host
